# -*- coding: utf-8 -*-
"""commands_keyword_extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/petermr/semanticClimate/blob/main/keyword_extraction/code/commands_keyword_extraction.ipynb
"""

!git clone  https://github.com/petermr/semanticClimate.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/semanticClimate/keyword_extraction/code/

!python -m spacy download en_core_web_lg

!pip install -r requirement.txt

!python keyword_extraction.py \
--html_path /content/semanticClimate/ipcc/ar6/wg3/Chapter07/fulltext.flow.html \
--saving_path /content/ \
--method 'gensim'