dot -Tsvg /Users/pm286/workspace//pygetpapers/dependencies.dot -opygetpapers/dependencies.svg
dot -Tsvg /Users/pm286/workspace//docanalysis-old/dependencies.dot -odocanalysis-old/dependencies.svg
dot -Tsvg /Users/pm286/workspace//docanalysis-old/docanalysis/dependencies.dot -odocanalysis/dependencies.svg
dot -Tsvg /Users/pm286/workspace//amilib/amilib/dependencies.dot -oamilib/dependencies.svg
dot -Tsvg /Users/pm286/workspace//amilib/amilib/dependencies_ami.dot -oamilib/dependencies_ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/cephis/target/classes/org/contentmine/cproject/args/prenorma.dot -oargs/prenorma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/cephis/target/classes/org/contentmine/graphics/layout/asgt/math7.dot -oasgt/math7.svg
dot -Tsvg /Users/pm286/workspace//cmdev/cephis/target/dotty/poms.dot -odotty/poms.svg
dot -Tsvg /Users/pm286/workspace//cmdev/cephis/src/main/resources/org/contentmine/cproject/args/prenorma.dot -oargs/prenorma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/cephis/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot -oasgt/math7.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/ami/plugins/ami.dot -oplugins/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/ami/plugins/phylotree/ami.dot -ophylotree/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/norma/normasmall.dot -onorma/normasmall.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/norma/norma.dot -onorma/norma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/ami/plugins/ami.dot -oplugins/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot -ophylotree/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/norma/normasmall.dot -onorma/normasmall.svg
dot -Tsvg /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/norma/norma.dot -onorma/norma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/ami/plugins/ami.dot -oplugins/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/ami/plugins/phylotree/ami.dot -ophylotree/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/cproject/args/prenorma.dot -oargs/prenorma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/graphics/layout/asgt/math7.dot -oasgt/math7.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/norma/normasmall.dot -onorma/normasmall.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/norma/norma.dot -onorma/norma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/ami/plugins/ami.dot -oplugins/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot -ophylotree/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/cproject/args/prenorma.dot -oargs/prenorma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot -oasgt/math7.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/norma/normasmall.dot -onorma/normasmall.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/norma/norma.dot -onorma/norma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/ami/plugins/ami.dot -oplugins/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot -ophylotree/ami.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/cproject/args/prenorma.dot -oargs/prenorma.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot -oasgt/math7.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/norma/normasmall.dot -onorma/normasmall.svg
dot -Tsvg /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/norma/norma.dot -onorma/norma.svg
dot -Tsvg /Users/pm286/workspace//pyamihtml/test/resources/ipcc/cleaned_content/vivliostyle/docs/images/graph.dot -oimages/graph.svg
dot -Tsvg /Users/pm286/workspace//pyamihtml/assets/dependencies2.dot -oassets/dependencies2.svg
dot -Tsvg /Users/pm286/workspace//pyamihtml/assets/dependencies.dot -oassets/dependencies.svg
dot -Tsvg /Users/pm286/workspace//pyamiimage/test/resources/test.dot -oresources/test.svg
dot -Tsvg /Users/pm286/workspace//pyamiimage/dependencies.dot -opyamiimage/dependencies.svg
dot -Tsvg /Users/pm286/workspace//amiclimate/climate/dependencies.dot -oclimate/dependencies.svg
dot -Tsvg /Users/pm286/workspace//docanalysis/dependencies.dot -odocanalysis/dependencies.svg
dot -Tsvg /Users/pm286/workspace//cma3-test/vivlio-dir/docs/images/graph.dot -oimages/graph.svg
