cp /Users/pm286/workspace//pygetpapers/dependencies.dot pygetpapers/dependencies.dot
cp /Users/pm286/workspace//cmdev/cephis/target/classes/org/contentmine/cproject/args/prenorma.dot args/prenorma.dot
cp /Users/pm286/workspace//cmdev/cephis/target/classes/org/contentmine/graphics/layout/asgt/math7.dot asgt/math7.dot
cp /Users/pm286/workspace//cmdev/cephis/target/dotty/poms.dot dotty/poms.dot
cp /Users/pm286/workspace//cmdev/cephis/src/main/resources/org/contentmine/cproject/args/prenorma.dot args/prenorma.dot
cp /Users/pm286/workspace//cmdev/cephis/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot asgt/math7.dot
cp /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/ami/plugins/ami.dot plugins/ami.dot
cp /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/ami/plugins/phylotree/ami.dot phylotree/ami.dot
cp /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/norma/normasmall.dot norma/normasmall.dot
cp /Users/pm286/workspace//cmdev/normami/target/classes/org/contentmine/norma/norma.dot norma/norma.dot
cp /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/ami/plugins/ami.dot plugins/ami.dot
cp /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot phylotree/ami.dot
cp /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/norma/normasmall.dot norma/normasmall.dot
cp /Users/pm286/workspace//cmdev/normami/src/main/resources/org/contentmine/norma/norma.dot norma/norma.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/ami/plugins/ami.dot plugins/ami.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/ami/plugins/phylotree/ami.dot phylotree/ami.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/cproject/args/prenorma.dot args/prenorma.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/graphics/layout/asgt/math7.dot asgt/math7.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/norma/normasmall.dot norma/normasmall.dot
cp /Users/pm286/workspace//cmdev/ami3/target/classes/org/contentmine/norma/norma.dot norma/norma.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/ami/plugins/ami.dot plugins/ami.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot phylotree/ami.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/cproject/args/prenorma.dot args/prenorma.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot asgt/math7.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/norma/normasmall.dot norma/normasmall.dot
cp /Users/pm286/workspace//cmdev/ami3/src/main/resources/org/contentmine/norma/norma.dot norma/norma.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/ami/plugins/ami.dot plugins/ami.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/ami/plugins/phylotree/ami.dot phylotree/ami.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/cproject/args/prenorma.dot args/prenorma.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/graphics/layout/asgt/math7.dot asgt/math7.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/norma/normasmall.dot norma/normasmall.dot
cp /Users/pm286/workspace//cmdev/ami-temp/ami3/src/main/resources/org/contentmine/norma/norma.dot norma/norma.dot
cp /Users/pm286/workspace//pyamihtml/test/resources/ipcc/cleaned_content/vivliostyle/docs/images/graph.dot images/graph.dot
cp /Users/pm286/workspace//pyamihtml/assets/dependencies2.dot assets/dependencies2.dot
cp /Users/pm286/workspace//pyamihtml/assets/dependencies.dot assets/dependencies.dot
cp /Users/pm286/workspace//pyamiimage/test/resources/test.dot resources/test.dot
cp /Users/pm286/workspace//pyamiimage/dependencies.dot pyamiimage/dependencies.dot
cp /Users/pm286/workspace//amiclimate/climate/dependencies.dot climate/dependencies.dot
cp /Users/pm286/workspace//docanalysis/dependencies.dot docanalysis/dependencies.dot
cp /Users/pm286/workspace//cma3-test/vivlio-dir/docs/images/graph.dot images/graph.dot
