(function($){function scroll_progress(item,options){this.item=$(item);var defaults={section:'section',logging:false};this.options=$.extend(true,defaults,options);this.init();}
scroll_progress.prototype={init:function(){var plugin_instance=this;var plugin_item=plugin_instance.item;var plugin_settings=plugin_instance.options;var plugin_elements=plugin_settings.elements;if(plugin_settings.logging==true){console.log('scroll progress init');}
if(plugin_settings.logging==true){console.log($(plugin_settings.section));}
$(window).scroll(function(){var scroll_top=$(this).scrollTop();if(plugin_settings.logging==true){}
$(plugin_settings.section).each(function(i){var this_top=$(this).offset().top;var height=$(this).height();var this_bottom=this_top+height;var percent,percent_decimal=0;var progress_item=plugin_item.find('li:eq('+i+')');progress_item.removeClass('active');if(plugin_settings.logging==true){}
if(scroll_top<this_top){progress_item.removeClass('active').removeClass('over-half');plugin_instance._object_rotation(progress_item.find('.circle'),0);}else if(scroll_top>=this_top&&scroll_top<=this_bottom){if(plugin_settings.logging==true){console.log(' currently visible: '+i);}
progress_item.addClass('active');percent=((scroll_top-this_top)/height)*100;var circle_right_rotate=plugin_instance._object_rotation($('#progress .circle.right'));var circle_left_rotate=plugin_instance._object_rotation($('#progress .circle.left'));var new_rotate=Math.ceil((360*(percent/100))/5)*5;if(new_rotate<=10){new_rotate=0;}
if(new_rotate<=180){progress_item.removeClass('over-half');plugin_instance._object_rotation(progress_item.find('.circle'),new_rotate);}else{progress_item.addClass('over-half');plugin_instance._object_rotation(progress_item.find('.circle.right'),180);plugin_instance._object_rotation(progress_item.find('.circle.left'),new_rotate);}}else if(scroll_top>this_bottom){progress_item.addClass('over-half');plugin_instance._object_rotation(progress_item.find('.circle.right'),180);plugin_instance._object_rotation(progress_item.find('.circle.left'),360);}else{plugin_instance._object_rotation(progress_item.find('.circle'),0);}});});},_object_rotation:function(element,new_value){var matrix=element.css("-webkit-transform")||element.css("-moz-transform")||element.css("-ms-transform")||element.css("-o-transform")||element.css("transform");if(matrix!=='none'&&typeof matrix!=='undefined'){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));}else{var angle=0;}
if(typeof new_value!=='undefined'){element.css("-webkit-transform",'rotate('+new_value+'deg)').css("-moz-transform",'rotate('+new_value+'deg)').css("-ms-transform",'rotate('+new_value+'deg)').css("-o-transform",'rotate('+new_value+'deg)').css("transform",'rotate('+new_value+'deg)');}else{return angle;}}}
$.fn.scroll_progress=function(opt){var args=Array.prototype.slice.call(arguments,1);return this.each(function(){var item=$(this);var instance=item.data('scroll_progress');if(!instance){item.data('scroll_progress',new scroll_progress(this,opt));}else{if(typeof opt==='string'){instance[opt].apply(instance,args);}}});}}(jQuery));